'use strict';'require baseclass';'require wifimgr/layer2 as layer2';async function load_all(){const[radiosRes,ifacesRes,mldsRes,clientsRes,uplinksRes,sysinfoRes,relaydRes]=await Promise.all([layer2.radio_get_all(),layer2.iface_get_all(),layer2.mld_get_all(),layer2.clients_get_all(),layer2.uplink_get_all(),layer2.system_get_info(),layer2.relayd_get()]);return{radios:radiosRes.ok?radiosRes.data:[],ifaces:ifacesRes.ok?ifacesRes.data:[],mlds:mldsRes.ok?mldsRes.data:[],clients:clientsRes.ok?clientsRes.data:[],uplinks:uplinksRes.ok?uplinksRes.data:[],sysinfo:sysinfoRes.ok?sysinfoRes.data:null,relayd:relaydRes.ok?relaydRes.data:{active:false,uplink_net:null},_errors:[!radiosRes.ok?'radio_get_all: '+radiosRes.error:null,!ifacesRes.ok?'iface_get_all: '+ifacesRes.error:null,!mldsRes.ok?'mld_get_all: '+mldsRes.error:null,!clientsRes.ok?'clients_get_all: '+clientsRes.error:null,].filter(Boolean)};}
async function load_diag(){const[sysinfoRes,logsRes,tp0,tp1,tp2]=await Promise.all([layer2.system_get_info(),layer2.system_get_logs(),layer2.system_get_txpower_info(0),layer2.system_get_txpower_info(1),layer2.system_get_txpower_info(2)]);return{sysinfo:sysinfoRes.ok?sysinfoRes.data:null,logs:logsRes,txpower:[tp0,tp1,tp2]};}
async function load_channels(){const res=await layer2.radio_get_channels('radio0');return res.ok?res.data:[];}
async function scan(radio_id){const res=await layer2.uplink_scan(radio_id);return res.ok?res.data:[];}
function start_apply(type){layer2.system_apply(type);}
async function poll_apply(){return layer2.system_apply_poll();}
async function wizard_ap(radio_id,params){const enc=params.encryption||(radio_id==='radio2'?'sae':'psk2');const write=Object.assign({encryption:enc},params);delete write.radio_id;const res=await layer2.iface_add(radio_id,'ap',write);if(!res.ok)return{ok:false,sid:null,restartRequired:'none',errors:res.errors||[]};return{ok:true,sid:res.sid,restartRequired:'wifi',errors:[]};}
async function wizard_mlo(radio_ids,params){const enc=params.encryption||'sae-mixed';const write=Object.assign({encryption:enc},params);const res=await layer2.mld_add(radio_ids,write);if(!res.ok)return{ok:false,sid:null,restartRequired:'none',errors:res.errors||[]};return{ok:true,sid:res.sid,restartRequired:'reboot',errors:[]};}
async function wizard_sta(radio_id,params){const isMlo=params.mlo==='1'||params.mlo===true;const enc=params.encryption||(isMlo?'sae':'psk2');if(isMlo){const mloParams=Object.assign({},params,{encryption:enc,mlo:true});const res=await layer2.uplink_connect(radio_id,mloParams);if(!res.ok)return{ok:false,sid:null,restartRequired:'none',errors:res.errors||[]};return{ok:true,sid:res.sid,restartRequired:'wifi',errors:[]};}
const write=Object.assign({encryption:enc,network:params.network||'wwan'},params);const res=await layer2.iface_add(radio_id,'sta',write);if(!res.ok)return{ok:false,sid:null,restartRequired:'none',errors:res.errors||[]};return{ok:true,sid:res.sid,restartRequired:'wifi',errors:[]};}
async function wizard_relayd(radio_id,params){const enc=params.encryption||'none';const write=Object.assign({},params,{encryption:enc,network:'relayd_up'});delete write.wds;const staRes=await layer2.iface_add(radio_id,'sta',write);if(!staRes.ok)return{ok:false,sid:null,restartRequired:'none',errors:staRes.errors||[]};const relRes=await layer2.relayd_setup('relayd_up','lan');if(!relRes.ok){await layer2.iface_remove(staRes.sid);return{ok:false,sid:null,restartRequired:'none',errors:['relayd_setup failed']};}
return{ok:true,sid:staRes.sid,restartRequired:'wifi',errors:[]};}
async function wizard_repeater(uplink_radio_id,ap_radio_id,uplink_params,ap_params){const staEnc=uplink_params.encryption||'psk2';const staWrite=Object.assign({encryption:staEnc,network:'wwan',repeater:'1'},uplink_params);const staRes=await layer2.iface_add(uplink_radio_id,'sta',staWrite);if(!staRes.ok)return{ok:false,sta_sid:null,ap_sid:null,restartRequired:'none',errors:staRes.errors||[]};const apEnc=ap_params.encryption||(ap_radio_id==='radio2'?'sae':'psk2');const apWrite=Object.assign({encryption:apEnc,network:'lan',repeater:'1'},ap_params);const apRes=await layer2.iface_add(ap_radio_id,'ap',apWrite);if(!apRes.ok)return{ok:false,sta_sid:staRes.sid,ap_sid:null,restartRequired:'none',errors:apRes.errors||[]};await layer2.fw_wan_add_network('wwan');return{ok:true,sta_sid:staRes.sid,ap_sid:apRes.sid,restartRequired:'wifi',errors:[]};}
async function wizard_country(country){const errors=[];for(const rid of['radio0','radio1','radio2']){const res=await layer2.radio_set(rid,{country});if(!res.ok){errors.push(...(res.errors||['radio_set failed: '+rid]));break;}}
if(errors.length)return{ok:false,restartRequired:'none',errors};return{ok:true,restartRequired:'reboot',errors:[]};}
const Layer3={load_all,load_diag,load_channels,scan,start_apply,poll_apply,wizard_ap,wizard_mlo,wizard_sta,wizard_relayd,wizard_repeater,wizard_country};return baseclass.extend(Layer3);